// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY1y54mGx-js88udE32Yna9WXTdeijPGg',
    appId: '1:829996874632:web:d2610095bb5d4cf0e8583d',
    messagingSenderId: '829996874632',
    projectId: 'chat-app-c9cb7',
    authDomain: 'chat-app-c9cb7.firebaseapp.com',
    storageBucket: 'chat-app-c9cb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7y-Shr0YK7c2itDt0p0G3tQ-iU--Rec8',
    appId: '1:829996874632:android:ed274afbc502e703e8583d',
    messagingSenderId: '829996874632',
    projectId: 'chat-app-c9cb7',
    storageBucket: 'chat-app-c9cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDuWBCm9zlEZm-EpstBDpUkz7gq23pdTo',
    appId: '1:829996874632:ios:c885883f63be28a5e8583d',
    messagingSenderId: '829996874632',
    projectId: 'chat-app-c9cb7',
    storageBucket: 'chat-app-c9cb7.appspot.com',
    iosClientId: '829996874632-rohu218gh1a8iqqugog48t1uvh1frggs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDuWBCm9zlEZm-EpstBDpUkz7gq23pdTo',
    appId: '1:829996874632:ios:c885883f63be28a5e8583d',
    messagingSenderId: '829996874632',
    projectId: 'chat-app-c9cb7',
    storageBucket: 'chat-app-c9cb7.appspot.com',
    iosClientId: '829996874632-rohu218gh1a8iqqugog48t1uvh1frggs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
